"""create initial schema

Revision ID: ba02daaf3f6b
Revises: 
Create Date: 2026-05-17 16:38:18.844223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba02daaf3f6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alternatives',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_alternatives_project_code')
    )
    op.create_table('classes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_classes_project_code')
    )
    op.create_table('criteria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('beneficio', 'custo', name='criterion_kind'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_criteria_project_code')
    )
    op.create_table('fuzzy_terms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('l', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('m', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('u', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('term_type', sa.Enum('alternative', 'weight', name='term_type'), nullable=False),
    sa.CheckConstraint('l <= m AND m <= u', name='ck_fuzzy_terms_lmu_order'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', 'term_type', name='uq_fuzzy_terms_project_code_type')
    )
    op.create_table('criteria_weights',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('criterion_id', sa.BigInteger(), nullable=False),
    sa.Column('weight_term_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weight_term_id'], ['fuzzy_terms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'criterion_id', name='uq_criteria_weights_project_crit')
    )
    op.create_table('criterion_class_thresholds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('criterion_id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.BigInteger(), nullable=False),
    sa.Column('min_alternative_term_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['min_alternative_term_id'], ['fuzzy_terms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('criterion_id', 'class_id', name='uq_criterion_class_threshold')
    )
    op.create_table('criterion_descriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('criterion_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('alternative_term_id', sa.BigInteger(), nullable=True),
    sa.Column('weight_term_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['alternative_term_id'], ['fuzzy_terms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weight_term_id'], ['fuzzy_terms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('alternative_id', sa.BigInteger(), nullable=False),
    sa.Column('criterion_id', sa.BigInteger(), nullable=False),
    sa.Column('criterion_description_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['alternative_id'], ['alternatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criterion_description_id'], ['criterion_descriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'alternative_id', 'criterion_id', name='uq_evaluations_project_alt_crit')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    op.drop_table('criterion_descriptions')
    op.drop_table('criterion_class_thresholds')
    op.drop_table('criteria_weights')
    op.drop_table('fuzzy_terms')
    op.drop_table('criteria')
    op.drop_table('classes')
    op.drop_table('alternatives')
    op.drop_table('projects')
    # ### end Alembic commands ###
